name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: ordinarydeveloper
        password: ${{ secrets.DOCKER_HUB_KEY }}
        
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        file: production.Dockerfile
        tags: ordinarydeveloper/filmio-frontend:latest
